import type { PololuMotor } from "../common";
import { kgfcmToNm, ozInTokgfcm } from "../common";

export const hp6vMotors: PololuMotor[] = [
  {
    id: "1093",
    series: "Micro Metal",
    voltage: 6,
    motorType: "HP 6V",
    gearRatio: "30:1",
    rpmNoLoad: 1000,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(7.9)),
    stallCurrentA: 1.6,
    freeRunCurrentA: 0.1,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/1093",
  },
  {
    id: "998",
    series: "Micro Metal",
    voltage: 6,
    motorType: "HP 6V",
    gearRatio: "50:1",
    rpmNoLoad: 590,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(12)),
    stallCurrentA: 1.6,
    freeRunCurrentA: 0.1,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/998",
  },
  {
    id: "2361",
    series: "Micro Metal",
    voltage: 6,
    motorType: "HP 6V",
    gearRatio: "75:1",
    rpmNoLoad: 410,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(18)),
    stallCurrentA: 1.6,
    freeRunCurrentA: 0.1,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/2361",
  },
  {
    id: "1101",
    series: "Micro Metal",
    voltage: 6,
    motorType: "HP 6V",
    gearRatio: "100:1",
    rpmNoLoad: 310,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(24)),
    stallCurrentA: 1.6,
    freeRunCurrentA: 0.1,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/1101",
  },
  {
    id: "997",
    series: "Micro Metal",
    voltage: 6,
    motorType: "HP 6V",
    gearRatio: "150:1",
    rpmNoLoad: 210,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(33)),
    stallCurrentA: 1.6,
    freeRunCurrentA: 0.1,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/997",
  },
  {
    id: "996",
    series: "Micro Metal",
    voltage: 6,
    motorType: "HP 6V",
    gearRatio: "210:1",
    rpmNoLoad: 150,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(42)),
    stallCurrentA: 1.6,
    freeRunCurrentA: 0.1,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/996",
  },
  {
    id: "995",
    series: "Micro Metal",
    voltage: 6,
    motorType: "HP 6V",
    gearRatio: "250:1",
    rpmNoLoad: 120,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(47)),
    stallCurrentA: 1.6,
    freeRunCurrentA: 0.1,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/995",
  },
  {
    id: "994",
    series: "Micro Metal",
    voltage: 6,
    motorType: "HP 6V",
    gearRatio: "298:1",
    rpmNoLoad: 100,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(56)),
    stallCurrentA: 1.6,
    freeRunCurrentA: 0.1,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/994",
  },
];
