import type { PololuMotor } from "../common";
import { kgfcmToNm, ozInTokgfcm } from "../common";

export const hpcb6vMotors: PololuMotor[] = [
  {
    id: "3062",
    series: "Micro Metal",
    voltage: 6,
    motorType: "HPCB 6V",
    gearRatio: "30:1",
    rpmNoLoad: 1100,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(6.2)),
    stallCurrentA: 1.5,
    freeRunCurrentA: 0.15,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/3062",
  },
  {
    id: "3063",
    series: "Micro Metal",
    voltage: 6,
    motorType: "HPCB 6V",
    gearRatio: "50:1",
    rpmNoLoad: 650,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(10)),
    stallCurrentA: 1.5,
    freeRunCurrentA: 0.15,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/3063",
  },
  {
    id: "3064",
    series: "Micro Metal",
    voltage: 6,
    motorType: "HPCB 6V",
    gearRatio: "75:1",
    rpmNoLoad: 430,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(15)),
    stallCurrentA: 1.5,
    freeRunCurrentA: 0.15,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/3064",
  },
  {
    id: "3065",
    series: "Micro Metal",
    voltage: 6,
    motorType: "HPCB 6V",
    gearRatio: "100:1",
    rpmNoLoad: 330,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(22)),
    stallCurrentA: 1.5,
    freeRunCurrentA: 0.15,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/3065",
  },
  {
    id: "3066",
    series: "Micro Metal",
    voltage: 6,
    motorType: "HPCB 6V",
    gearRatio: "150:1",
    rpmNoLoad: 220,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(28)),
    stallCurrentA: 1.5,
    freeRunCurrentA: 0.15,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/3066",
  },
  {
    id: "3067",
    series: "Micro Metal",
    voltage: 6,
    motorType: "HPCB 6V",
    gearRatio: "210:1",
    rpmNoLoad: 160,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(39)),
    stallCurrentA: 1.5,
    freeRunCurrentA: 0.15,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/3067",
  },
  {
    id: "3068",
    series: "Micro Metal",
    voltage: 6,
    motorType: "HPCB 6V",
    gearRatio: "250:1",
    rpmNoLoad: 130,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(44)),
    stallCurrentA: 1.5,
    freeRunCurrentA: 0.15,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/3068",
  },
  {
    id: "3069",
    series: "Micro Metal",
    voltage: 6,
    motorType: "HPCB 6V",
    gearRatio: "298:1",
    rpmNoLoad: 110,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(47)),
    stallCurrentA: 1.5,
    freeRunCurrentA: 0.15,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/3069",
  },
];
