import type { PololuMotor } from "../common";
import { kgfcmToNm, ozInTokgfcm } from "../common";

export const hpcb12vMotors: PololuMotor[] = [
  {
    id: "3038",
    series: "Micro Metal",
    voltage: 12,
    motorType: "HPCB 12V",
    gearRatio: "30:1",
    rpmNoLoad: 1100,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(5.4)),
    stallCurrentA: 0.75,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/3038",
  },
  {
    id: "3039",
    series: "Micro Metal",
    voltage: 12,
    motorType: "HPCB 12V",
    gearRatio: "50:1",
    rpmNoLoad: 650,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(9.3)),
    stallCurrentA: 0.75,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/3039",
  },
  {
    id: "3040",
    series: "Micro Metal",
    voltage: 12,
    motorType: "HPCB 12V",
    gearRatio: "75:1",
    rpmNoLoad: 450,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(14)),
    stallCurrentA: 0.75,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/3040",
  },
  {
    id: "3041",
    series: "Micro Metal",
    voltage: 12,
    motorType: "HPCB 12V",
    gearRatio: "100:1",
    rpmNoLoad: 330,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(18)),
    stallCurrentA: 0.75,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/3041",
  },
  {
    id: "3042",
    series: "Micro Metal",
    voltage: 12,
    motorType: "HPCB 12V",
    gearRatio: "150:1",
    rpmNoLoad: 220,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(25)),
    stallCurrentA: 0.75,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/3042",
  },
  {
    id: "3043",
    series: "Micro Metal",
    voltage: 12,
    motorType: "HPCB 12V",
    gearRatio: "210:1",
    rpmNoLoad: 160,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(35)),
    stallCurrentA: 0.75,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/3043",
  },
  {
    id: "3044",
    series: "Micro Metal",
    voltage: 12,
    motorType: "HPCB 12V",
    gearRatio: "250:1",
    rpmNoLoad: 130,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(42)),
    stallCurrentA: 0.75,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/3044",
  },
  {
    id: "3045",
    series: "Micro Metal",
    voltage: 12,
    motorType: "HPCB 12V",
    gearRatio: "298:1",
    rpmNoLoad: 110,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(46)),
    stallCurrentA: 0.75,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/3045",
  },
];
