import type { PololuMotor } from "../common";
import { kgfcmToNm, ozInTokgfcm } from "../common";

export const lp6vMotors: PololuMotor[] = [
  {
    id: "993",
    series: "Micro Metal",
    voltage: 6,
    motorType: "LP 6V",
    gearRatio: "30:1",
    rpmNoLoad: 450,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(4.0)),
    stallCurrentA: 0.36,
    freeRunCurrentA: 0.04,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/993",
  },
  {
    id: "1098",
    series: "Micro Metal",
    voltage: 6,
    motorType: "LP 6V",
    gearRatio: "50:1",
    rpmNoLoad: 270,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(6.1)),
    stallCurrentA: 0.36,
    freeRunCurrentA: 0.04,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/1098",
  },
  {
    id: "2360",
    series: "Micro Metal",
    voltage: 6,
    motorType: "LP 6V",
    gearRatio: "75:1",
    rpmNoLoad: 180,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(8.9)),
    stallCurrentA: 0.36,
    freeRunCurrentA: 0.04,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/2360",
  },
  {
    id: "992",
    series: "Micro Metal",
    voltage: 6,
    motorType: "LP 6V",
    gearRatio: "100:1",
    rpmNoLoad: 130,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(10)),
    stallCurrentA: 0.36,
    freeRunCurrentA: 0.04,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/992",
  },
  {
    id: "1097",
    series: "Micro Metal",
    voltage: 6,
    motorType: "LP 6V",
    gearRatio: "150:1",
    rpmNoLoad: 90,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(15)),
    stallCurrentA: 0.36,
    freeRunCurrentA: 0.04,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/1097",
  },
  {
    id: "1096",
    series: "Micro Metal",
    voltage: 6,
    motorType: "LP 6V",
    gearRatio: "210:1",
    rpmNoLoad: 65,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(22)),
    stallCurrentA: 0.36,
    freeRunCurrentA: 0.04,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/1096",
  },
  {
    id: "1095",
    series: "Micro Metal",
    voltage: 6,
    motorType: "LP 6V",
    gearRatio: "250:1",
    rpmNoLoad: 54,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(24)),
    stallCurrentA: 0.36,
    freeRunCurrentA: 0.04,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/1095",
  },
  {
    id: "1094",
    series: "Micro Metal",
    voltage: 6,
    motorType: "LP 6V",
    gearRatio: "298:1",
    rpmNoLoad: 45,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(28)),
    stallCurrentA: 0.36,
    freeRunCurrentA: 0.04,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/1094",
  },
];
