import type { PololuMotor } from "../common";
import { kgfcmToNm, ozInTokgfcm } from "../common";

export const mp6vMotors: PololuMotor[] = [
  {
    id: "2364",
    series: "Micro Metal",
    voltage: 6,
    motorType: "MP 6V",
    gearRatio: "30:1",
    rpmNoLoad: 720,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(4.6)),
    stallCurrentA: 0.67,
    freeRunCurrentA: 0.07,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/2364",
  },
  {
    id: "2365",
    series: "Micro Metal",
    voltage: 6,
    motorType: "MP 6V",
    gearRatio: "50:1",
    rpmNoLoad: 420,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(7.5)),
    stallCurrentA: 0.67,
    freeRunCurrentA: 0.07,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/2365",
  },
  {
    id: "2366",
    series: "Micro Metal",
    voltage: 6,
    motorType: "MP 6V",
    gearRatio: "75:1",
    rpmNoLoad: 290,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(11)),
    stallCurrentA: 0.67,
    freeRunCurrentA: 0.07,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/2366",
  },
  {
    id: "2367",
    series: "Micro Metal",
    voltage: 6,
    motorType: "MP 6V",
    gearRatio: "100:1",
    rpmNoLoad: 220,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(13)),
    stallCurrentA: 0.67,
    freeRunCurrentA: 0.07,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/2367",
  },
  {
    id: "2368",
    series: "Micro Metal",
    voltage: 6,
    motorType: "MP 6V",
    gearRatio: "150:1",
    rpmNoLoad: 150,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(18)),
    stallCurrentA: 0.67,
    freeRunCurrentA: 0.07,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/2368",
  },
  {
    id: "2369",
    series: "Micro Metal",
    voltage: 6,
    motorType: "MP 6V",
    gearRatio: "210:1",
    rpmNoLoad: 100,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(24)),
    stallCurrentA: 0.67,
    freeRunCurrentA: 0.07,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/2369",
  },
  {
    id: "2370",
    series: "Micro Metal",
    voltage: 6,
    motorType: "MP 6V",
    gearRatio: "250:1",
    rpmNoLoad: 88,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(31)),
    stallCurrentA: 0.67,
    freeRunCurrentA: 0.07,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/2370",
  },
  {
    id: "2371",
    series: "Micro Metal",
    voltage: 6,
    motorType: "MP 6V",
    gearRatio: "298:1",
    rpmNoLoad: 73,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(33)),
    stallCurrentA: 0.67,
    freeRunCurrentA: 0.07,
    outputShaftDiameter: 3,
    supplier: "Pololu",
    url: "https://pololu.com/product/2371",
  },
];
