import type { PololuMotor } from "../common";
import { kgfcmToNm, ozInTokgfcm } from "../common";

export const cb12vMotors: PololuMotor[] = [
  {
    id: "20D-12V-63",
    series: "20D",
    voltage: 12,
    motorType: "CB 12V",
    gearRatio: "63:1",
    rpmNoLoad: 220,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(64)),
    stallCurrentA: 1.6,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/3476",
  },
  {
    id: "20D-12V-78",
    series: "20D",
    voltage: 12,
    motorType: "CB 12V",
    gearRatio: "78:1",
    rpmNoLoad: 180,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(75)),
    stallCurrentA: 1.6,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/3477",
  },
  {
    id: "20D-12V-100",
    series: "20D",
    voltage: 12,
    motorType: "CB 12V",
    gearRatio: "100:1",
    rpmNoLoad: 140,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(85)),
    stallCurrentA: 1.6,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/3478",
  },
  {
    id: "20D-12V-125",
    series: "20D",
    voltage: 12,
    motorType: "CB 12V",
    gearRatio: "125:1",
    rpmNoLoad: 110,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(110)),
    stallCurrentA: 1.6,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/3479",
  },
  {
    id: "20D-12V-156",
    series: "20D",
    voltage: 12,
    motorType: "CB 12V",
    gearRatio: "156:1",
    rpmNoLoad: 89,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(130)),
    stallCurrentA: 1.6,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/3480",
  },
];
