import type { PololuMotor } from "../common";
import { kgfcmToNm, ozInTokgfcm } from "../common";

export const cb6vMotors: PololuMotor[] = [
  {
    id: "20D-6V-63",
    series: "20D",
    voltage: 6,
    motorType: "CB 6V",
    gearRatio: "63:1",
    rpmNoLoad: 230,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(56)),
    stallCurrentA: 2.9,
    freeRunCurrentA: 0.15,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/3702",
  },
  {
    id: "20D-6V-78",
    series: "20D",
    voltage: 6,
    motorType: "CB 6V",
    gearRatio: "78:1",
    rpmNoLoad: 180,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(61)),
    stallCurrentA: 2.9,
    freeRunCurrentA: 0.15,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/3703",
  },
  {
    id: "20D-6V-100",
    series: "20D",
    voltage: 6,
    motorType: "CB 6V",
    gearRatio: "100:1",
    rpmNoLoad: 140,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(75)),
    stallCurrentA: 2.9,
    freeRunCurrentA: 0.15,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/3704",
  },
  {
    id: "20D-6V-125",
    series: "20D",
    voltage: 6,
    motorType: "CB 6V",
    gearRatio: "125:1",
    rpmNoLoad: 110,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(89)),
    stallCurrentA: 2.9,
    freeRunCurrentA: 0.15,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/3705",
  },
  {
    id: "20D-6V-156",
    series: "20D",
    voltage: 6,
    motorType: "CB 6V",
    gearRatio: "156:1",
    rpmNoLoad: 91,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(110)),
    stallCurrentA: 2.9,
    freeRunCurrentA: 0.15,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/3706",
  },
];
