import type { PololuMotor } from "../common";
import { kgfcmToNm, ozInTokgfcm } from "../common";

export const motor12vMotors: PololuMotor[] = [
  {
    id: "4741",
    series: "37D",
    voltage: 12,
    motorType: "12V",
    gearRatio: "19:1",
    rpmNoLoad: 530,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(120)),
    stallCurrentA: 5.5,
    freeRunCurrentA: 0.2,
    outputShaftDiameter: 6,
    supplier: "Pololu",
    url: "https://pololu.com/product/4741",
  },
  {
    id: "4742",
    series: "37D",
    voltage: 12,
    motorType: "12V",
    gearRatio: "30:1",
    rpmNoLoad: 330,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(190)),
    stallCurrentA: 5.5,
    freeRunCurrentA: 0.2,
    outputShaftDiameter: 6,
    supplier: "Pololu",
    url: "https://pololu.com/product/4742",
  },
  {
    id: "4743",
    series: "37D",
    voltage: 12,
    motorType: "12V",
    gearRatio: "50:1",
    rpmNoLoad: 200,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(290)),
    stallCurrentA: 5.5,
    freeRunCurrentA: 0.2,
    outputShaftDiameter: 6,
    supplier: "Pololu",
    url: "https://pololu.com/product/4743",
  },
  {
    id: "4744",
    series: "37D",
    voltage: 12,
    motorType: "12V",
    gearRatio: "70:1",
    rpmNoLoad: 150,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(380)),
    stallCurrentA: 5.5,
    freeRunCurrentA: 0.2,
    outputShaftDiameter: 6,
    supplier: "Pololu",
    url: "https://pololu.com/product/4744",
  },
  {
    id: "4745",
    series: "37D",
    voltage: 12,
    motorType: "12V",
    gearRatio: "100:1",
    rpmNoLoad: 100,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(470)),
    stallCurrentA: 5.5,
    freeRunCurrentA: 0.2,
    outputShaftDiameter: 6,
    supplier: "Pololu",
    url: "https://pololu.com/product/4745",
  },
];
