import type { PololuMotor } from "../common";
import { kgfcmToNm, ozInTokgfcm } from "../common";

export const motor24vMotors: PololuMotor[] = [
  {
    id: "4681",
    series: "37D",
    voltage: 24,
    motorType: "24V",
    gearRatio: "19:1",
    rpmNoLoad: 530,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(130)),
    stallCurrentA: 3.0,
    freeRunCurrentA: 0.1,
    outputShaftDiameter: 6,
    supplier: "Pololu",
    url: "https://pololu.com/product/4681",
  },
  {
    id: "4682",
    series: "37D",
    voltage: 24,
    motorType: "24V",
    gearRatio: "30:1",
    rpmNoLoad: 330,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(210)),
    stallCurrentA: 3.0,
    freeRunCurrentA: 0.1,
    outputShaftDiameter: 6,
    supplier: "Pololu",
    url: "https://pololu.com/product/4682",
  },
  {
    id: "4683",
    series: "37D",
    voltage: 24,
    motorType: "24V",
    gearRatio: "50:1",
    rpmNoLoad: 200,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(320)),
    stallCurrentA: 3.0,
    freeRunCurrentA: 0.1,
    outputShaftDiameter: 6,
    supplier: "Pololu",
    url: "https://pololu.com/product/4683",
  },
  {
    id: "4684",
    series: "37D",
    voltage: 24,
    motorType: "24V",
    gearRatio: "70:1",
    rpmNoLoad: 140,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(430)),
    stallCurrentA: 3.0,
    freeRunCurrentA: 0.1,
    outputShaftDiameter: 6,
    supplier: "Pololu",
    url: "https://pololu.com/product/4684",
  },
  {
    id: "4685",
    series: "37D",
    voltage: 24,
    motorType: "24V",
    gearRatio: "100:1",
    rpmNoLoad: 100,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(540)),
    stallCurrentA: 3.0,
    freeRunCurrentA: 0.1,
    outputShaftDiameter: 6,
    supplier: "Pololu",
    url: "https://pololu.com/product/4685",
  },
];
