import type { PololuMotor } from "../common";
import { kgfcmToNm, ozInTokgfcm } from "../common";

export const hp6vMotors: PololuMotor[] = [
  {
    id: "1572",
    series: "25D",
    voltage: 6,
    motorType: "HP 6V",
    gearRatio: "20.4:1",
    rpmNoLoad: 480,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(67)),
    stallCurrentA: 6.0,
    freeRunCurrentA: 0.42,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/1572",
  },
  {
    id: "1573",
    series: "25D",
    voltage: 6,
    motorType: "HP 6V",
    gearRatio: "34:1",
    rpmNoLoad: 290,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(94)),
    stallCurrentA: 6.0,
    freeRunCurrentA: 0.42,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/1573",
  },
  {
    id: "1574",
    series: "25D",
    voltage: 6,
    motorType: "HP 6V",
    gearRatio: "47:1",
    rpmNoLoad: 210,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(130)),
    stallCurrentA: 6.0,
    freeRunCurrentA: 0.42,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/1574",
  },
  {
    id: "1575",
    series: "25D",
    voltage: 6,
    motorType: "HP 6V",
    gearRatio: "75:1",
    rpmNoLoad: 130,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(190)),
    stallCurrentA: 6.0,
    freeRunCurrentA: 0.42,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/1575",
  },
  {
    id: "1576",
    series: "25D",
    voltage: 6,
    motorType: "HP 6V",
    gearRatio: "99:1",
    rpmNoLoad: 99,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(210)),
    stallCurrentA: 6.0,
    freeRunCurrentA: 0.42,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/1576",
  },
];
