import type { PololuMotor } from "../common";
import { kgfcmToNm, ozInTokgfcm } from "../common";

export const mp12vMotors: PololuMotor[] = [
  {
    id: "3227",
    series: "25D",
    voltage: 12,
    motorType: "MP 12V",
    gearRatio: "20.4:1",
    rpmNoLoad: 380,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(44)),
    stallCurrentA: 1.8,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/3227",
  },
  {
    id: "3228",
    series: "25D",
    voltage: 12,
    motorType: "MP 12V",
    gearRatio: "34:1",
    rpmNoLoad: 230,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(65)),
    stallCurrentA: 1.8,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/3228",
  },
  {
    id: "3229",
    series: "25D",
    voltage: 12,
    motorType: "MP 12V",
    gearRatio: "47:1",
    rpmNoLoad: 170,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(89)),
    stallCurrentA: 1.8,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/3229",
  },
  {
    id: "3230",
    series: "25D",
    voltage: 12,
    motorType: "MP 12V",
    gearRatio: "75:1",
    rpmNoLoad: 100,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(120)),
    stallCurrentA: 1.8,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/3230",
  },
  {
    id: "3231",
    series: "25D",
    voltage: 12,
    motorType: "MP 12V",
    gearRatio: "99:1",
    rpmNoLoad: 79,
    torqueRatedNm: kgfcmToNm(ozInTokgfcm(150)),
    stallCurrentA: 1.8,
    freeRunCurrentA: 0.08,
    outputShaftDiameter: 4,
    supplier: "Pololu",
    url: "https://pololu.com/product/3231",
  },
];
